### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported angle: -180

### ISSUE THREAD

**Issue by visro** [JeroenMols/LandscapeVideoCamera#19]
java.lang.IllegalArgumentException: Unsupported angle: -180
    at android.media.MediaRecorder.setOrientationHint(MediaRecorder.java:419)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.configureMediaRecorder(VideoRecorder.java:148)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initRecorder(VideoRecorder.java:122)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.startRecording(VideoRecorder.java:87)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.toggleRecording(VideoRecorder.java:80)

**Comment by JeroenMols** [comment]
@visro Any update on this? I cannot reproduce the issue locally.

**Comment by visro** [comment]
I fixed the issue Unsupported angle: -180
Now i found new issue "No quality level found" in device with vga camera

**Comment by JeroenMols** [comment]
Anything I can merge so others also benefit from the fix?

**Comment by JeroenMols** [comment]
Closing as no follow up from reporter
