### ISSUE TITLE
Can't capture video : Camera disabled or in use by other process

### ISSUE THREAD

**Issue by fbayle** [JeroenMols/LandscapeVideoCamera#37]
Hi, 

I can't get the camera working. When the phone is in portrait, I get the icon asking to rotate the phone, but when I do that, I get this error : 

Can't capture video : Camera disabled or in use by other process

My code is basic :

```
CaptureConfiguration configuration = new CaptureConfiguration(PredefinedCaptureConfigurations.CaptureResolution.RES_1080P, PredefinedCaptureConfigurations.CaptureQuality.HIGH, 120, 200000, true, false);

String filename= Environment.getExternalStorageDirectory().getAbsolutePath() + "/myvideo.mp4";

final Intent intent = new Intent(getActivity(), VideoCaptureActivity.class);
intent.putExtra(VideoCaptureActivity.EXTRA_CAPTURE_CONFIGURATION, configuration);
intent.putExtra(VideoCaptureActivity.EXTRA_OUTPUT_FILENAME, filename);
startActivityForResult(intent, 101);
```

The phone is an Honor 5x, with Android 6.0. What am I doing wrong ?

The console : 

```
W/CameraBase: An error occurred while connecting to camera: 0
E/Camera-JNI: android_hardware_Camera_native_setup Error: -1 
E/Camera: Camera new cameraInitNormal:-1
W/System.err: java.lang.RuntimeException: Unknown camera error(-1)
W/System.err:     at android.hardware.Camera.<init>(Camera.java:578)
W/System.err:     at android.hardware.Camera.open(Camera.java:399)
W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.NativeCamera.openNativeCamera(NativeCamera.java:48)
W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.CameraWrapper.openCamera(CameraWrapper.java:53)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initializeCameraAndPreview(VideoRecorder.java:64)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.<init>(VideoRecorder.java:59)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.initializeRecordingUI(VideoCaptureActivity.java:89)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.onCreate(VideoCaptureActivity.java:73)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6372)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2513)
W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4136)
W/System.err:     at android.app.ActivityThread.access$1000(ActivityThread.java:168)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:150)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5639)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
E/VideoCapture_Exception: Unable to open camera - Camera disabled or in use by other process
W/System.err: com.jmolsmobile.landscapevideocapture.camera.OpenCameraException: Camera disabled or in use by other process
W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.CameraWrapper.openCamera(CameraWrapper.java:56)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initializeCameraAndPreview(VideoRecorder.java:64)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.<init>(VideoRecorder.java:59)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.initializeRecordingUI(VideoCaptureActivity.java:89)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.onCreate(VideoCaptureActivity.java:73)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6372)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2513)
W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4136)
W/System.err:     at android.app.ActivityThread.access$1000(ActivityThread.java:168)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:150)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5639)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
W/CameraBase: An error occurred while connecting to camera: 0
E/Camera-JNI: android_hardware_Camera_native_setup Error: -1 
E/Camera: Camera new cameraInitNormal:-1
W/System.err: java.lang.RuntimeException: Unknown camera error(-1)
W/System.err:     at android.hardware.Camera.<init>(Camera.java:578)
W/System.err:     at android.hardware.Camera.open(Camera.java:399)
W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.NativeCamera.openNativeCamera(NativeCamera.java:48)
W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.CameraWrapper.openCamera(CameraWrapper.java:53)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initializeCameraAndPreview(VideoRecorder.java:64)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.<init>(VideoRecorder.java:59)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.initializeRecordingUI(VideoCaptureActivity.java:89)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.onCreate(VideoCaptureActivity.java:73)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6372)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2513)
W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:168)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:150)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5639)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
E/VideoCapture_Exception: Unable to open camera - Camera disabled or in use by other process
W/System.err: com.jmolsmobile.landscapevideocapture.camera.OpenCameraException: Camera disabled or in use by other process
W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.CameraWrapper.openCamera(CameraWrapper.java:56)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initializeCameraAndPreview(VideoRecorder.java:64)
W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.<init>(VideoRecorder.java:59)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.initializeRecordingUI(VideoCaptureActivity.java:89)
W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.onCreate(VideoCaptureActivity.java:73)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6372)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2513)
W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:168)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:150)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5639)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```

**Comment by kevalpatel2106** [comment]
@fbayle Can you check this on the device running lower than 23? Also, make sure you added camera permission in manifest and  do you handle runtime permissions? 

Because this line `E/VideoCapture_Exception: Unable to open camera - Camera disabled or in use by other process` error log clearly indicates that `OpenCameraException(OpenType.INUSE)` exception is thrown.

**Comment by fbayle** [comment]
Thank you for your quick answer. 

I've put those in the manifest : 

```
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.INTERNET"/>
```

And here is my gradle file 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "24.0.3"
    defaultConfig {
        applicationId "com.xxxxx.xxxxx"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.github.JeroenMols:LandscapeVideoCamera:1.2.2'
    testCompile 'junit:junit:4.12'
}
```

**Comment by JeroenMols** [comment]
Can I conclude that the problem was that you didn't request the camera permission at runtime?

**Comment by fbayle** [comment]
No, the problem is that it does work with sdk 22 but not with sdk 23.

**Comment by kevalpatel2106** [comment]
@fbayle Yeah, that is because runtime permissions were introduced in API 23. So on API < 23, permissions are automatically granted, but for API >=23 you need to ask the user to grant permission.

I think you should read about runtime permissions from [here](https://developer.android.com/training/permissions/requesting.html) first.

**Comment by JeroenMols** [comment]
Thanks for the stellar support @kevalpatel2106 !
Closing the issue as resolved
